version: "3"
services: 
    php-laravel:
        container_name: php-laravel 
        build: ./docker/php
        image: practice/php-laravel
        environment: 
            HOME: /home/laravel
            PATH: $PATH:/home/laravel/.composer/vendor/bin
        volumes: 
            - ./laravel:/var/www/laravel
            - ./docker/php/init.d:/etc/init.d
        tty: true
    mysql:
        container_name: mysql
        build: ./docker/mysql
        image: practice/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: laravel
        volumes:
            - ./docker/mysql/store:/var/lib/mysql
        ports:
            - 3306:3306
        tty: true
    nginx:
        container_name: nginx
        build: ./docker/nginx
        image: practice/nginx
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 1000:8080
        tty: true
        