version: "3"
services: 
    laravel:
        container_name: laravel
        build: .
        image: practice/laravel
        volumes: 
            - ./laravel:/var/www/laravel
        tty: true
        