version: "3"
services: 
    php-api:
        container_name: php-api
        build: ./docker/php
        image: practice/php-api
        volumes: 
            - ./src:/var/www/slim
            - ./docker/php/init.d:/etc/init.d
        tty: true
        ports:
            - 8080:8080
        depends_on: 
            - mysql
    mysql:
        container_name: mysql
        build: ./docker/mysql
        image: practice/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: laravel
        volumes:
            - ./docker/mysql/store:/var/lib/mysql
        ports:
            - 3306:3306
        tty: true
    nginx:
        container_name: nginx
        build: ./docker/nginx
        image: practice/nginx
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/usr/share/nginx
        ports:
            - 1000:8080
        tty: true
