version: "3"
services: 
    php-api:
        container_name: php-api
        build: ./docker/php
        image: practice/php-api
        volumes: 
            - ./api-framework:/var/www
        tty: true
        depends_on: 
            - mysql
    mysql:
        container_name: mysql
        build: ./docker/mysql
        image: practice/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_USER_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        volumes:
            - ./docker/mysql/store:/var/lib/mysql
        ports:
            - "3306:3306"
        tty: true
    nginx:
        container_name: nginx
        build: ./docker/nginx
        image: practice/nginx
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
        ports:
            - "80:80"
        tty: true
        depends_on:
            - php-api
